# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07ad2d744b30f62f14efb8921eb6ae4341a47ce7b20997b5a0ee56f82cfc514f806d17c159fabb2a023de6cad2a186ed5fc0851860ce8941dd1255e6efe0a215

test:
  secret_key_base: a3f4235bb2c68d83e994ce1e6de4180340ee4098f7323b8d1ce713f980d54f9f6a463702f19695026f7cd2f3a8066386a9bb8a7833be15abbab172f574aef96a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
